mybatis:
  #匹配sql语句的映射文件的位置，classpat代表在resources下
  mapper-locations: classpath:mapper/*.xml
  #以下两个配置可以省略，然后在mapper映射文件中配置也是可以的。
  #使用type-aliases-package中指定entity扫描包类让mybatis自定扫描到自定义的entity
  type-aliases-package: com.example.LinuxSpringBoot.domain

  #... 其他配置信息
  configuration-properties:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
#  configuration:
#    #   开启驼峰uName自动映射到u_name
#    map-underscore-to-camel-case: true
