spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.130.22.229:13306/SpringBoot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
      username: root
      password:
      #????????????????????????init????????getConnection?
      initialSize: 0
      #???????
      maxActive: 20
      #??????,???????
      minIdle: 1
      #????????,????????????????????maxWait???????????????????????????????useUnfairLock???true??????
      maxWait: 60000
      #??????????????????????????????
      #??????filter:stat????filter:log4j??sql???filter:wall
      filters: stat
      #??????
      #1) Destroy????????????2) testWhileIdle?????????testWhileIdle?????
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      #???????????sql???????????
      #??validationQuery?null?testOnBorrow?testOnReturn?testWhileIdle??????
      validationQuery: SELECT 'x'
      #?????true?????????????????????????
      #????????timeBetweenEvictionRunsMillis???validationQuery?????????
      testWhileIdle: true
      #???????validationQuery????????????????????
      testOnBorrow: false
      #???????validationQuery????????????????????
      testOnReturn: false
      #???PSCache???????0????0??poolPreparedStatements???????true?
      #?Druid??????Oracle?PSCache??????????????????????????100
      maxOpenPreparedStatements: 100
      # 开启连接池回收
      remove-abandoned: true
      # 超时连接回收时间，单位秒
      remove-abandoned-timeout: 20
      # 回收连接时打印日志
      log-abandoned: true